# docker-compose.yml
services:
  backend:
    build: ./BackEnd
    env_file: ./BackEnd/.env
    networks: [app-network]

  frontend:
    build: ./FrontEnd
    env_file: ./FrontEnd/.env
    depends_on: [backend]
    networks: [app-network]

networks:
  app-network:
    driver: bridge

# docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d