# Dockerfile.dev para desenvolvimento com hot reload backend NestJS
FROM node:22-alpine
WORKDIR /app

RUN corepack enable && corepack prepare pnpm@latest --activate

# Copia dependências primeiro
COPY pnpm-lock.yaml package.json ./

RUN pnpm install

# O código será montado via volume no Docker Compose, 
# mas copiamos aqui para o build da imagem não vir vazio
COPY . .

EXPOSE 3001

# Comando padrão do Nest para Hot Reload
CMD ["pnpm", "run", "start:dev"]
