FROM mongo:8.0

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    unzip \
    tar \
    gzip \
    bash \
    && curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
    && unzip awscliv2.zip \
    && ./aws/install \
    && rm -rf awscliv2.zip aws \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY scripts/ /app/scripts/

RUN chmod +x /app/scripts/*.sh

# Keep original entrypoint so mongo tools work
ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]