name: Delete merged branch

on:
  pull_request:
    types: [closed]

jobs:
  delete_branch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Delete merged branch
        uses: peter-evans/delete-branch@v2
        with:
          branch: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
